### ISSUE TITLE
Render big images in 'n' chunks to avoid 'out of memory'

### ISSUE THREAD

**Issue by SunboX** [phoboslab/WebGLImageFilter#14]
On mobile devices, like Firefox OS phones with low memory, it's not possible to apply those effects to larger images (like from 8 MP cameras).

Quote from a stackoverflow answer to the question how to deal with this:

> So the way to deal with that is that you subdivide your image into smaller tiles and process each tile  one at a time.
> 
> There are two ways you can deal with borders if you have filter kernels.
> - You could pass in 9 textures and branch on texture lookup to address the correct one (that might be slow, some GPUs don't support branching and will execute all codepaths). Border textures would just be 2x2 so would have little ram footprint. Note that between textures there would be no interpolation, so don't rely on it, or substitute your own.
> - You could add a half kernel sized border around each tile taking pixels from neighboring tiles in a preprocessing step.

[Source: http://stackoverflow.com/a/15039655/1692735]

**Comment by phoboslab** [comment]
This would be extremely complicated to get right. A tiled rendering solution would also use more RAM in total. Which still would be fine if - as the answer on SO suggests - the problem is not the RAM or max texture size, but rather the frame buffer size.

Maybe just use a 2D Canvas, `getImageData()` and do the filtering straight in JavaScript on the CPU, or scale down your input image before applying the filter.

**Comment by mreinstein** [comment]
I would think that for low power/mobile devices it might make sense to not activate filter effects at all. I think this issue can be closed?
