### ISSUE TITLE
About the performance of  WebGLImageFilter 

### ISSUE THREAD

**Issue by finscn** [phoboslab/WebGLImageFilter#7]
Could I use WebGLImageFilter in the game for dynamic filter?

If my offscreen-canvas about 512*512 , How many FPS   the  WebGLImageFilter can reach ?

**Comment by mreinstein** [comment]
I've done some investigation on this too, because I also would like to use WebGLImageFilter in a game render loop.  My setup:

```javascript
const filter = new WebGLImageFilter()
filter.addFilter('hue', 180)
const filteredImage = filter.apply(gameCanvas)
// put the canvas that gets written to by WebGLImageFilter into the page so we can see it
document.body.appendChild(filteredImage) 


function gameLoop () {
    // do lots of drawing to gameCanvas here ...

    filter.apply(gameCanvas)
 
    requestAnimationFrame(gameLoop)
}

gameLoop()
```

when I run this, I see the correct results in my game (filter applied as expected) but the bulk of the time is actually being spent re-compiling the gl shader program:

<img width="495" alt="Screen Shot 2020-04-24 at 10 22 53 AM" src="https://user-images.githubusercontent.com/718067/80239827-b6f27680-8615-11ea-80ed-be6bed2b33fd.png">


@phoboslab  Am I calling this API in the right way?
I'm wondering if we could somehow cache the shader programs, when we're not changing the filter?

**Comment by mreinstein** [comment]
I added a very simple program cache. Here is my updated code for the hue filter. Only 3 lines were modified:

```javascript
_filter.colorMatrix = function( matrix ) {
	// Create a Float32 Array and normalize the offset component to 0-1
	var m = new Float32Array(matrix);
	m[4] /= 255;
	m[9] /= 255;
	m[14] /= 255;
	m[19] /= 255;

	// Can we ignore the alpha value? Makes things a bit faster.
	var shader = (1==m[18]&&0==m[3]&&0==m[8]&&0==m[13]&&0==m[15]&&0==m[16]&&0==m[17]&&0==m[19])
		? _filter.colorMatrix.SHADER.WITHOUT_ALPHA
		: _filter.colorMatrix.SHADER.WITH_ALPHA;
	
	// I added these 2 lines, leverage a cache for shader program to avoid re-computing it each time
	var program = window.shaderProgramCache || _compileShader(shader);
	window.shaderProgramCache = program;

	// I commented this out to use the cache when available
	//var program = _compileShader(shader);

	gl.uniform1fv(program.uniform.m, m);
	_draw();
};
```

When I run the updated code, I see _significantly_ better performance:

<img width="334" alt="Screen Shot 2020-04-24 at 10 56 40 AM" src="https://user-images.githubusercontent.com/718067/80242524-5580d680-861a-11ea-91c4-61dbed18d1c2.png">


If this is something we want to apply across all of the programs, it would likely make a huge difference, and probably make this thing fairly usable in real time. thoughts?

**Comment by phoboslab** [comment]
Oh wow, I totally missed that the cache isn't working. Thanks for the fix!
